//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.05 at 07:23:20 PM IST 
//


package com.App.integration.models.contentInfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paraseq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paraType", propOrder = {
	"autoParaId",	
    "paraseq",
    "content"
})
public class ParaType {
	
    protected int autoParaId;
    protected int paraseq;
    @XmlElement(required = true)
    protected String content;
    protected FileInfoType fileInfo;

    public FileInfoType getFileInfo() {
		return fileInfo;
	}

	public void setFileInfo(FileInfoType fileInfo) {
		this.fileInfo = fileInfo;
	}
    
    /**
	 * @return the autoParaId
	 */
	public int getAutoParaId() {
		return autoParaId;
	}

	/**
	 * @param autoParaId the autoParaId to set
	 */
	public void setAutoParaId(int autoParaId) {
		this.autoParaId = autoParaId;
	}

	/**
     * Gets the value of the paraseq property.
     * 
     */
    public int getParaseq() {
        return paraseq;
    }

    /**
     * Sets the value of the paraseq property.
     * 
     */
    public void setParaseq(int value) {
        this.paraseq = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

}
